[rendering]
skin = assets/skin2.png
# skin = assets/default.png
# skin = assets/default.png
# skin = assets/default.png
colored_ghost = false
# 0-100
ghost_opacity = 80

[controls]
move_left = j
move_right = l
rotate_cw = d
rotate_ccw = s
rotate_180 = a
hard_drop = space
soft_drop = k
hold = lshift

[tuning]
das = 110
arr = 0
soft_drop_interval = 0
das_preserve_charge = true

[game]
# ms. >0 = timed gravity, 0 = 20G (instant drop), <0 = no gravity
gravity_interval = -1
# ms. >0 = timed lock, 0 = instant lock on ground, <0 = no auto-lock (hard drop only)
lock_delay = -1
garbage_delay = 250
max_lock_resets = 15
infinite_hold = true
# ms. delay after soft lock before hard drop is accepted (prevents misdrops)
hard_drop_delay = 50
