[rendering]
skin = assets/skin4.png
colored_ghost = true
# 0-100
ghost_opacity = 60

[controls]
move_left = left
move_right = right
rotate_cw = up
rotate_ccw = z
rotate_180 = a
hard_drop = space
soft_drop = down
hold = c
undo = u

[tuning]
das = 110
arr = 0
soft_drop_interval = 0
das_preserve_charge = true

[game]
# ms. >0 = timed gravity, 0 = 20G (instant drop), <0 = no gravity
gravity_interval = -1
# ms. >0 = timed lock, 0 = 20G, <0 = 0 gravity
lock_delay = -1
max_lock_resets = 15
infinite_hold = true
# ms. delay after soft lock before hard drop is accepted (prevents misdrops)
hard_drop_delay = 50
garbage_delay = 250
